### ISSUE TITLE
Problem na serwerze

### ISSUE THREAD

**Issue by Markuu** [TheDoctor0/sklep-sms#6]
Witam.

Wgrałem & zainstalowałem sklep sms na stronę WWW oraz serwer 1.6, wszystko ładnie, serwer dodałem w panelu admina, ustawiłem usługę, ceny, itd. Podpiąłem po stronie serwera bazę danych w pliku .cfg, natomiast komenda nie działa, a w konsoli występuje następujący problem:

L 05/08/2019 - 12:39:53: [AMXX] Plugin ("sklep_sms.amxx") is setting itself as failed.
L 05/08/2019 - 12:39:53: [AMXX] Plugin says: Ten serwer nie znajduje sie w bazie danych SklepuSMS.
L 05/08/2019 - 12:39:53: [AMXX] Run time error 1 (plugin "sklep_sms.amxx") - forced exit

Proszę o pomoc.

**Comment by TheDoctor0** [comment]
Co tu dużo mówić, komunikat jest dość jednoznaczny.
Plugin nie może pobrać z bazy sklepu serwera o określonym IP i porcie.
Możesz spróbować wywołać sobie zapytanie wypełniając IP i port w klauzuli WHERE i sprawdzić, czy zwróci prawidłowe dane, tj. id serwera i podstawowe ustawienia sklepu:
```
SELECT a.id, a.sms_service, b.*, c.data, c.id AS 'default' 
FROM `ss_servers` AS a 
LEFT JOIN `ss_settings` AS b ON 1=1 
LEFT JOIN `ss_transaction_services` AS c ON (b.value = c.id OR a.sms_service = c.id) 
WHERE b.key IN ('shop_url', 'random_key', 'sms_service', 'vat', 'currency') AND a.ip = '%s' AND a.port = '%s';
```

**Comment by Markuu** [comment]
Wykonałem zapytanie i wszystko zdaje się być jak najbardziej w porządku.

![Untitled](https://user-images.githubusercontent.com/22773647/57471656-f2bcf080-728b-11e9-8613-2838822e6373.png)

**Comment by TheDoctor0** [comment]
Id serwera jest niezerowe, a ono właśnie jest sprawdzane i jeśli jest równe 0 plugin generuje failstate "Ten serwer nie znajduje sie w bazie danych SklepuSMS".
O ile serwer na pewno podpięty jest pod tą bazę, sklep powinien działać bez problemu i na starcie zaktualizować wersję serwera widoczną w panelu administracyjnym.
Możesz jeszcze oczywiście dla pewności jeszcze raz pobrać release i najlepiej skompilować sobie główny plugin lokalnie przed wgraniem na serwer.

**Comment by Markuu** [comment]
Wyczyściłem bazę, stworzyłem nową z innym użytkownikiem oraz nazwą bazy, nadałem wszystkie przywileje, zrobiłem reinstalację sklepu, wypełniłem ustawienia, dodałem serwer, skompilowałem plugin lokalnie, wgrałem, zmieniłem dane do bazy w .cfg, zrestartowałem i to samo... Nie mam pomysłów.

**Comment by TheDoctor0** [comment]
Jeśli chcesz, możesz wysłać mi tymczasowe dane do ftp serwera na maila widocznego na moim profilu.
Zajrzę i spróbuję zdebugować problem lokalnie.

**Comment by TheDoctor0** [comment]
Problem wynikał z błędnej konfiguracji serwera.
