### ISSUE TITLE
Błąd ArraySize i ilością załadowanych usług

### ISSUE THREAD

**Issue by daffyyyy** [TheDoctor0/sklep-sms#81]
Już wiem dlaczego, w pluginie jest `register_library("shop_sms");` 

Wyjaśnione, dzięki wielkie za odpowiedź

_Originally posted by @eryk172 in https://github.com/TheDoctor0/sklep-sms/issues/5#issuecomment-489360613_

Zmieniłem to na sklep_sms tak samo w .inc i nic nie pomogło.

Mam 2 usługi do kupienia na serwerze, ale konsola wypluwa, że załadowano tylko 1.
Gdy wpiszę /sklepsms pojawia mi się menu 1. BRAK TEKSTU, 2. Twoje usługi, gdy wcisnę 1 wywala w konsoli serwera taki błąd

```
L 12/29/2019 - 15:31:21: Invalid array handle provided (0)
L 12/29/2019 - 15:31:21: [AMXX] Displaying debug trace (plugin "sklep_sms.amxx", version "3.6.6")
L 12/29/2019 - 15:31:21: [AMXX] Run time error 10: native error (native "ArraySize")
L 12/29/2019 - 15:31:21: [AMXX]    [0] sklep_sms.sma::shop_menu_handle (line 302)

```

**Comment by TheDoctor0** [comment]
> Mam 2 usługi do kupienia na serwerze, ale konsola wypluwa, że załadowano tylko 1.
Radziłbym sprawdzić czy obie usługi są odpowiednio skonfigurowane po webowej stronie sklepu.

Brak nazwy usługi w głównym menu wskazywałby na nieprawidłowo napisany plugin usługi lub błąd w jej konfiguracji.
