### ISSUE TITLE
Błąd instalacji sklepu

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/sklep-sms#84]
Witam,
Mam problem przy instalacji sklepu po stronie WWW. wszystkie katalogi mam wgranę przechodzę do instalacji gdzie mam zmienić atrybuty zapisów do poszczególnych katalogów. Tak też robię, daję pełny zapis dla katalogów (777) ale w okienku instalacji dalej widnieje, że jest brak zapisu i błąd (bad)

**Comment by TheDoctor0** [comment]
Jeśli jesteś w 100% pewny, że wskazane katalogi są zapisywalne, możesz wyczyścić plik [install/storage/full/files_priv.txt](https://github.com/TheDoctor0/sklep-sms/blob/master/install/storage/full/files_priv.txt) i skończyć instalację.
